In [6]:
#import the required libraries
import numpy as np
import csv

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Step 1 : Read the Data!

In [25]:
#give path of the source-file and store that path in a variable named census
data_file = '/content/drive/MyDrive/Untitled folder/makeSenseOfCensus.csv'
census = data_file

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [26]:
data = np.genfromtxt(census, delimiter = ',' , skip_header =1 )

# printing the data

print("\nData: \n\n", data)



Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [10]:
#print the type of data
print(type(data))

<class 'numpy.ndarray'>


# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [11]:
new_record = [[50,9,4,1,0,0,40,0]]
np.concatenate((data,new_record))


array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [12]:
data = np.concatenate((data, new_record), axis=0)

In [13]:
#display after appending the new record at the end of the array.
print(f"array({data}")

array([[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [ ]:
age = data[:,0]
print(age)

[39. 50. 38. ... 40. 39. 50.]


Find the max age and store it in a variable called 'max_age'.



In [ ]:
#print the max_age
max_age = np.max(age)
print(max_age)

90.0


Find the min age and store it in a variable called 'min_age'.

In [ ]:
#print the min_age
min_age = np.min(age)
print(min_age)

17.0


Find the mean of the age and store it in a variable called 'age_mean'.

In [ ]:
#print the age_mean
age_mean = np.mean(age)
print(age_mean)

38.06293706293706


Find the standard deviation of the age and store it in a variable called 'age_std'

In [ ]:
#print the age_std
age_std = np.std(age)
print(age_std)

13.341478176165857


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [28]:
race = data[:,2]
race_0 = data[race==0]
race_1 = data[race==1]
race_2 = data[race==2]
race_3 = data[race==3]
race_4 = data[race==4]
print(race_0)

[[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]


Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [ ]:
#len_0
len_0 = len(race_0)
print(len_0)

10


In [ ]:
#len_1
len_1 = len(race_1)
print(len_1)

27


In [ ]:
#len_2
len_2 = len(race_2)
print(len_2)

110


In [ ]:
#len_3
len_3 = len(race_3)
print(len_3)

6


In [ ]:
#len_4
len_4 = len(race_4)
print(len_4)

848


Find out which is the race with the maximum no. of citizens

In [ ]:
race_with_max_citizens = np.max([len_0,len_1,len_2,len_3,len_4])
print(f"race4 : citizens :{race_with_max_citizens}")


race4 : citizens :848


Find out which is the race with the minimum no. of citizens

In [ ]:
race_with_min_citizens = np.min([len_0,len_1,len_2,len_3,len_4])
print(f"race3 : citizens :{race_with_min_citizens}")


race3 : citizens :6


Store the number associated with the maximum race in a variable called 'maximum_race'(For eg: if "len(race_5)" is the maximum, store 5 in 'maximum_race' because that is the index of the race having the maximum no. of citizens )

In [75]:
lengths = [len(race_0), len(race_1), len(race_2), len(race_3), len(race_4)]
maximum_race = np.argmax(lengths)
print("Maximum race:", maximum_race)

Maximum race: 4


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [76]:
lengths = [len(race_0), len(race_1), len(race_2), len(race_3), len(race_4)]
minority_race = np.argmin(lengths)
print("Minority race:", minority_race)


Minority race: 3


# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [17]:
#from age column, filter out age data > 60
senior_citizens = data[data[:, 0] > 60]
print(senior_citizens)

[[7.9000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.7000e+01 6.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+00 0.0000e+00]
 [7.6000e+01 1.4000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 1.0000e+00]
 [6.1000e+01 9.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [7.0000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [6.4000e+01 7.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 2.1790e+03
  4.0000e+01 0.0000e+00]
 [7.1000e+01 1.0000e+01 2.0000e+00 1.0000e+00 0.0000e+00 1.8160e+03
  2.0000e+00 0.0000e+00]
 [6.8000e+01 2.0000e+00 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.6000e+01 1.1000e+01 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.4000e+01 2.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [9.0000e+01 9.0000e+00 2.0000e+00 1.0000e+00 0.0000e+00 2.2060e+03
  

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [19]:
senior_citizens = data[data[:, 0] > 60]
working_hours_sum = senior_citizens[:, 6].sum()
print(f"Total working hours for senior citizens : {working_hours_sum}")

Total working hours for senior citizens : 1917.0


c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [21]:
senior_citizens_len = len(senior_citizens)
print(f"Number of senior citizens : {senior_citizens_len}")

Number of senior citizens : 61


d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [22]:
avg_working_hours = working_hours_sum / senior_citizens_len
print(f"Average working hours for senior citizens : {avg_working_hours}")

Average working hours for senior citizens : 31.42622950819672


e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [23]:
print(f"Average working hours for senior citizens : {avg_working_hours}")
if avg_working_hours > 25:
    print("Govt. policy is not followed.")
else:
    print("Govt. policy is followed.")

Average working hours for senior citizens : 31.42622950819672
Govt. policy is not followed.


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [24]:
high = census[census[:, 1] > 10]
low = census[census[:, 1] <= 10]

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [28. 13.  2. ...  0. 40.  0.]
 ...
 [45. 14.  4. ...  0. 45.  0.]
 [48. 13.  4. ...  0. 58.  1.]
 [39. 13.  4. ...  0. 50.  1.]]


Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [31]:
avg_pay_high = np.mean(high[:, 7])
print(f"Average pay for high educated people : {avg_pay_high:.2f}")

Average pay for high educated people : 0.43


In [32]:
avg_pay_low = np.mean(low[:, 7])
print(f"Average pay for low educated people : {avg_pay_low:.2f}")

Average pay for low educated people : 0.14
